apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube-postgresql
  namespace: sonar
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /persistent_volumes/pvc-sonarqube/postgre
    type: ''
  claimRef:
    name: data-sonar-postgresql-0
    namespace: sonar
