apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube-sonarqube
  namespace: sonar
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /persistent_volumes/pvc-sonarqube/sonarqube
    type: ''
  claimRef:
    name: sonar-sonarqube
    namespace: sonar
