---
# Source: sonarqube/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonar-sonarqube
  namespace: "sonar"
  labels:
    app.kubernetes.io/name: sonarqube
    helm.sh/chart: sonarqube-1.0.9
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  sonarqube-password: "SXBYdkx4ZGZBcQ=="
