---
# Source: sonarqube/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonar-sonarqube-foo
  namespace: "sonar"
  labels:
    app.kubernetes.io/name: sonarqube
    helm.sh/chart: sonarqube-1.0.9
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
