---
# Source: artifactory-oss/charts/artifactory/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-postgresql
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-10.3.18
    app.kubernetes.io/instance: artifactory
    app.kubernetes.io/managed-by: Helm
  namespace: artifactory
type: Opaque
data:
  postgresql-postgres-password: "Z05VQmhzempRVw=="
  postgresql-password: "RTNZVEJicmRoZQ=="
