---
# Source: sonarqube/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonar-postgresql
  namespace: sonar
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.17
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "S1p5aU10TURiNw=="
  password: "MmhJcmNjeDJXRQ=="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
