apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-artifactory
  namespace: artifactory
spec:
  rules:
  - host: artifactory.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: artifactory-artifactory-nginx
            port: 
              number: 80
