---
# Source: sonarqube/charts/postgresql/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: sonar-postgresql
  namespace: sonar
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.17
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: primary
  annotations:
spec:
  type: ClusterIP
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
      nodePort: null
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: sonar
    app.kubernetes.io/component: primary
