apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gogs
  namespace: gogs
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /persistent_volumes/pvc-gogs
    type: ''
  claimRef:
    name: pvc-gogs
    namespace: gogs
    