---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory
  labels:
    app: artifactory
    chart: artifactory-107.35.2
    heritage: Helm
    release: artifactory
type: Opaque
data:
