---
# Source: artifactory-oss/charts/artifactory/templates/artifactory-binarystore-secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: artifactory-binarystore
  labels:
    app: artifactory
    chart: artifactory-107.35.2
    heritage: Helm
    release: artifactory
stringData:
  binarystore.xml: |-
    <!-- File system filestore -->
    <config version="v1">
        <chain>
                <provider id="file-system" type="file-system"/>
        </chain>
    </config>
